# Generated by Django 5.0.7 on 2024-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_conversationlog_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationlog",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
