# Generated by Django 5.0.7 on 2024-09-05 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_grammarlesson_listeningtopic_writingtopic_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progress",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="progress",
            name="grammar_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="progress",
            name="listening_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="writing_progress",
            field=models.IntegerField(default=0),
        ),
    ]
