# Generated by Django 5.0.7 on 2024-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_grammarlesson_is_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="proficiency_level",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="completed_tasks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weekly_task_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="ConversationLog",
        ),
    ]
