# Generated by Django 5.0.7 on 2024-09-05 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_weeklytask_remove_userprofile_interests_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("audio_file", models.FileField(upload_to="audio/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="lessoncompletion",
            name="weekly_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.weeklytask",
            ),
        ),
        migrations.AddField(
            model_name="weeklytask",
            name="audio_file",
            field=models.FileField(
                default="audio/nightfall-future-bass-music-228100_nTLraq7.mp3",
                upload_to="audio/",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessoncompletion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lessoncompletion",
            name="speaking_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.speakingtopic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessoncompletion",
            unique_together={
                (
                    "user",
                    "lesson",
                    "writing_topic",
                    "listening_topic",
                    "speaking_topic",
                    "weekly_task",
                )
            },
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
