# Generated by Django 5.0.7 on 2024-09-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_speakingtopic_lessoncompletion_weekly_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speakingtopic",
            name="audio_file",
        ),
    ]
